### ISSUE TITLE
Trying to set blob name at runtime

### ISSUE THREAD

**Issue by csyvenky** [lcarli/NodeRed-Azure-Storage-Blob#6]
Hi,
I've been able to successfully configure this node in my NR flow and I am able to successfully upload image files to Azure blob storage. My issue is that I need to be able to save the node name dynamically (i need to save multiple files to Azure, not just continually over write the same blob). I tried using a function node trying to guess the property name in hopes that I could set the blob name property at runtime. Any chance of supporting this use-case?

**Comment by rasavant-ms** [comment]
Hello @csyvenky,
Can you tell me the detail of the msg.payload that you send to the Blob storage node? Is it a JSON?

**Comment by rasavant-ms** [comment]
This feature request has been added and the new npm package published with this change. Please make a note of the new repo for this package - [https://github.com/Azure/node-red-contrib-azure/tree/master/blob-storage](https://github.com/Azure/node-red-contrib-azure/tree/master/blob-storage``)
